version: '3.4'

services:
  new-api:
    image: calciumion/new-api:latest
    container_name: new-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    environment:
      - SQL_DSN=postgresql://newapi:1q2w3e4r@postgres:5432/new_api?sslmode=disable
      - REDIS_CONN_STRING=redis://:1q2w3e4r@redis:6379
      - TZ=Asia/Shanghai
      - SESSION_SECRET=9bb72908a871ce5c19a5b0a80ff4da90377d3a0faac038a2e9fc35d047e2fc16
      - ERROR_LOG_ENABLED=true
      - BATCH_UPDATE_ENABLED=true
      - GENERATE_DEFAULT_TOKEN=false
      - PGSSLMODE=disable
    depends_on:
      - redis
      - postgres
    networks:
      - new-api-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: ["redis-server", "--requirepass", "1q2w3e4r", "--appendonly", "yes"]
    volumes:
      - ./redis-data:/data
    networks:
      - new-api-network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: newapi
      POSTGRES_PASSWORD: 1q2w3e4r
      POSTGRES_DB: new_api
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - new-api-network

networks:
  new-api-network:
    driver: bridge
